### ISSUE TITLE
docs: metadata download required before running build

### ISSUE THREAD

**Issue by missinglink** [pelias/geonames#222]
since https://github.com/pelias/geonames/commit/020b18f7c81f8590bc6f358ca6f8507d63f32152 the `metadata/countryInfo.json` file is no longer available in the repo.

the readme says downloading the metadata is optional, although it now seems to be mandatory?

```bash
> pelias-geonames@0.0.0-semantic-release download /code/pelias/geonames
> node bin/download_data.js

module.js:327
    throw err;
    ^

Error: Cannot find module '../metadata/countryInfo'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/code/pelias/geonames/lib/validateISOCode.js:3:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

**Comment by orangejulius** [comment]
The metadata is supposed to be downloaded after `npm install` automatically (see https://github.com/pelias/geonames/blob/master/package.json#L15). I wonder why that's not working.

**Comment by missinglink** [comment]
oh that makes more sense, this is definitely not the case in k8s

**Comment by orangejulius** [comment]
Yeah, but the geonames Dockerfile [runs npm install](https://github.com/pelias/dockerfiles/blob/master/geonames/Dockerfile#L24), so shouldn't it be there anyway? Very weird. Maybe it's a path thing.

**Comment by orangejulius** [comment]
I just realized we should make this run automatically as part of any download (or, if needed, build). It's a very small file, and we do a similar thing with the index.txt file for whosonfirst.

**Comment by missinglink** [comment]
I preferred the old method of committing the metadata files in the module.

Making downloads compulsory at run time complicates things is the user has intermittent connectivity or the download server is unavailable.

What was the rationale in removing from the module?

**Comment by orangejulius** [comment]
That's a good point that the build itself should not require network once all the data is downloaded. So I think the current method might still be the best.

If we move the metadata file back into this repo, it will eventually be out of date, right? By having `npm install` also download the latest metadata, which already requires network access, and is run fairly frequently, we guarantee it's up to date, and don't have to include it ourselves.

Again this must be something weird happening in the kubernetes environment, since the [postinstall hook to download the metadata](https://github.com/pelias/geonames/blob/master/package.json#L15) has been working for a long time now.

**Comment by missinglink** [comment]
My understanding is that the metadata changes very infrequently.

**Comment by dianashk** [comment]
Figure out why this is happening in kubernetes and not in other stable environments.
